"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import posixpath
from django.contrib import admin
import logging
import ldap
from django_auth_ldap.config import *
from django_auth_ldap.config import LDAPSearch
import logging
from logging.handlers import RotatingFileHandler
from django.conf import settings

BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--1f*(48^z1u+da3kld0-k+w%j!8-70=3=j7u@))jmetms7ofx2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

#CSRF_TRUSTED_ORIGINS = ['http://172.16.1.61', 'http://localhost', 'https://172.16.1.61']

CSRF_TRUSTED_ORIGINS = ['http://10.100.0.34', 'http://localhost', 'http://demeter.ciaer.interna',  'https://sn.ciaer.interna']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login.apps.LoginConfig',
    'sn.apps.SnConfig',
    # 'tinymce',
    'ckeditor',
    'ckeditor_uploader',
    'rolepermissions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configurar a expiração da sessão para 30 minutos (30 * 60 segundos)
SESSION_COOKIE_AGE = 3800

ROOT_URLCONF = 'core.urls'


INTERNAL_IPS = [
    # ...
    '127.0.0.1',
    # ...
]

TEMPLATES = [
    {
        
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_LDAP_SERVER_URI = "ldap://10.100.0.1:389"
AUTH_LDAP_BIND_DN = "cn=django,ou=ciaer,dc=ciaer,dc=interna"
AUTH_LDAP_BIND_PASSWORD = "P0rM41s7"

AUTH_LDAP_USER_SEARCH = LDAPSearch(
#            "ou=CIAER,dc=ciaer,dc=interna", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
            "ou=CIAER,dc=ciaer,dc=interna", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"
            )

AUTH_LDAP_USER_ATTR_MAP = {
            "username": "sAMAccountName",
#            "username": "uid",
               "first_name": "name",
                    "last_name": "physicalDeliveryOfficeName",
			#"posto_nome": "cn",
                       "email": "mail",
}


# AUTHENTICATION_BACKENDS = [
#             'django_auth_ldap.backend.LDAPBackend',
#             'django.contrib.auth.backends.ModelBackend',
# ]

# AUTHENTICATION_BACKENDS = [
#              'core.backend.CustomLDAPBackend',
#                  'django.contrib.auth.backends.ModelBackend',
# ]


# Define o caminho para o diretório de logs dentro do seu projeto Django
LOGS_DIR = os.path.join(BASE_DIR, 'logs')

# Se o diretório de logs não existir, crie-o
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# Define o caminho completo para o arquivo de log
LOG_FILE_PATH = os.path.join(LOGS_DIR, 'django_auth_ldap.log')

# Configuração do logger
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',  # Ajuste o nível de log conforme necessário
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_FILE_PATH,
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django_auth_ldap': {
            'handlers': ['file'],
            'level': 'DEBUG',  # Ajuste o nível de log conforme necessário
            'propagate': True,
        },
    },
}




# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db2.sqlite3',
   }
}

# DATABASES = {
#       'default': {
#           'ENGINE': 'django.db.backends.mysql',
#           'NAME': 'sn',
#           'USER': 'demeterdb',
#           'PASSWORD': 'S1NdemeBD@01',
#           'HOST': 'localhost',
#           'PORT': '3306'
#       }
#  }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]






# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Caminho para os arquivos estáticos coletados
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    # '/var/www/arq_staticfiles',
]

# Caminho para os arquivos de mídia
MEDIA_URL = '/media/'
# MEDIA_ROOT = '/var/www/doc/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 


CKEDITOR_UPLOAD_PATH = "uploads/"




# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ROLEPERMISSIONS_MODULE = "core.roles"

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL ='/'
LOGOUT_REDIRECT_URL = "/"

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB



CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 1300,
    },
}

