# Generated by Django 4.2.16 on 2024-09-23 18:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=30, verbose_name='Destino')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('divisao', models.CharField(max_length=30, verbose_name='Divisão')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Divisão',
                'verbose_name_plural': 'Divisões',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=30, verbose_name='Tipo do documento')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(max_length=30, verbose_name='Setor')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('fk_divisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sn.divisao', verbose_name='Divisão')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Numeracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_despacho', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Despacho')),
                ('doc_sigad_origem', models.CharField(blank=True, max_length=200, null=True, verbose_name='SIGAD Origem')),
                ('doc_numero', models.IntegerField(blank=True, null=True, verbose_name='Número do documento')),
                ('title', models.CharField(max_length=200)),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sn.destino', verbose_name='Destino')),
                ('fk_divisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sn.divisao', verbose_name='Divisão')),
                ('fk_setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sn.setor', verbose_name='Setor')),
                ('fk_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sn.tipo', verbose_name='Tipo do Documento')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Numeros',
                'ordering': ['id'],
            },
        ),
    ]
