# Generated by Django 5.2.2 on 2025-07-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexo',
            old_name='documento',
            new_name='doc_numero',
        ),
        migrations.RenameField(
            model_name='encaminhamento',
            old_name='documento',
            new_name='doc_numero',
        ),
    ]
