# Generated by Django 5.2.2 on 2026-03-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0002_rename_documento_anexo_doc_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Om',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('om', models.CharField(max_length=100, verbose_name='OM')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OM',
                'verbose_name_plural': 'OMs',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='numeracao',
            options={'ordering': ['id'], 'verbose_name': 'Número', 'verbose_name_plural': 'Números'},
        ),
        migrations.AddField(
            model_name='divisao',
            name='fk_om',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sn.om', verbose_name='OM_Divisão'),
        ),
    ]
