# Generated by Django 5.2.2 on 2026-03-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn', '0004_divisao_fk_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['destino'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.AlterModelOptions(
            name='divisao',
            options={'ordering': ['divisao'], 'verbose_name': 'Divisão', 'verbose_name_plural': 'Divisões'},
        ),
        migrations.AlterModelOptions(
            name='numeracao',
            options={'ordering': ['-create_at'], 'verbose_name': 'Número', 'verbose_name_plural': 'Números'},
        ),
        migrations.AlterModelOptions(
            name='om',
            options={'ordering': ['om'], 'verbose_name': 'OM', 'verbose_name_plural': 'OMs'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['setor'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['tipo_doc'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.RemoveField(
            model_name='divisao',
            name='fk_user',
        ),
        migrations.AddField(
            model_name='destino',
            name='fk_om',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sn.om', verbose_name='OM'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='fk_om',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisoes', to='sn.om', verbose_name='OM'),
        ),
        migrations.AlterField(
            model_name='divisao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='numeracao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='om',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='fk_divisao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setores', to='sn.divisao', verbose_name='Divisão'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
